kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume2
  labels:
    type: local
    app: {{ .Values.namept }}
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs: 
    path: /kubedata/postgres 
    server: 192.168.48.139 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim2
  labels:
    app: {{ .Values.namept }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
