apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      nodeSelector: 
        kubernetes.io/hostname: {{ .Values.node }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}/{{ .Values.image.tag | default .Chart.AppVersion }}
        volumeMounts:
        - name: {{ .Values.volumeMounts.name }}
          mountPath: {{ .Values.volumeMounts.mountPath }}
        env: {{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value }}
        {{- end }}
        ports:
        - name: {{ .Values.name }}
          containerPort: {{ .Values.containerPort }}
        securityContext:
          privileged: {{ .Values.privileged }}
      volumes:
      - name: {{ .Values.volumes.name }}
        hostPath:               # <- the folder on the host machine.
          path: {{ .Values.hostPath.path }}

