apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.namepvc }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.namepv }}
  labels:
    type: {{ .Values.type }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  capacity:
    storage: {{ .Values.storagepv }}
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.hostPath.path }}


