apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name_s }}
spec:
  selector:
    role: {{ .Values.role }}
  ports: {{- range .Values.portss }}
    - name: {{ .name }}
      port: {{ .port }}
      {{ if .protocol }}
      protocol: {{ .protocol }}
      {{- end }}
  {{- end }}







