kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name_s }}
spec:
  ports:
    - name: {{ .Values.name }}
      port: {{ .Values.ports.port }}
      protocol: {{ .Values.ports.protocol }}
      targetPort: {{ .Values.ports.targetPort }}
  selector:
    app: {{ .Values.name_s }}






